language: python
sudo: false
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - "pypy"
install:
  - pip install pep8
script:
  # Guard against invalid escapes in strings, like '\s'. If this fails, a
  # string or docstring somewhere needs to be a raw string.
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.6" ];
        python -We:invalid -m compileall -f mpmath;
    fi
  - pep8
  - py.test
notifications:
  email: false
